### ISSUE TITLE
Enable piping

### ISSUE THREAD

**Issue by albinekb** [mixn/carbon-now-cli#12]
It would be cool if we could copy some code, then run `pbpaste | carbon-now` to make an image of the clipboard contents.

**Comment by mixn** [comment]
@albinekb Thanks for your input. :) I’ve added this one to the “ideas” pile, since I do believe that it could come in handy sometimes. Not my highest priority atm though, but certainly not against it, either.

**Comment by thib92** [comment]
I'll make a PR for this. Researching how I can output the file content in a format that will be caught correctly by `pbcopy`.

**Comment by mixn** [comment]
@thib92 I’m actually kind of already working on this. :)

**Comment by albinekb** [comment]
Yes, that's correct @mixn I mixed it up with pbcopy usage 👍

**Comment by thib92** [comment]
Oh, I thought about copying the file in the clipboard to paste it in a GUI program. I think this could be a cool feature as well, what do you think ?

**Comment by mixn** [comment]
Yep that’s #3. It should ideally not just work with `pbcopy` / on Mac, but be cross-env.

**Comment by thib92** [comment]
Cool! If you need help on this one then (code in `stdin`), I can help as well.

**Comment by mixn** [comment]
@albinekb @thib92 

After having lost all my work on this feature due to a broken Macbook and being super swamped with work, I’ve finally found the motivation and time to ship this (technically a 2nd time. 😄)

Ships with `v1.4.0`. :) Docs, if needed, can be found [https://github.com/mixn/carbon-now-cli#input-sources](here). 🎉 

Thank you for the idea and feedback! 🙏

**Comment by thib92** [comment]
Amazing work 👏 👏
