### ISSUE TITLE
Option to choose output image name

### ISSUE THREAD

**Issue by boudhayan-dev** [mixn/carbon-now-cli#18]
Is it possible for the user to define the output image's name ? It seems to me that successive usage of the tool ends up overwriting the previous carbon.png instead of creating a new carbon(1).png.

**Comment by mixn** [comment]
This now ships with the prerelease of `v1.1.0-0`. :) More infos on how to install it can be found [here](https://github.com/mixn/carbon-now-cli/issues/2#issuecomment-405096144).

@boudhayan-dev Please be aware that you might have the same issues you’ve had in #10, as I’ve not merged @Sneezoo’s PR yet, due to lack of feedback. Just a heads up. :)

**Comment by boudhayan-dev** [comment]
@mixn Thank you. The new additional features are very helpful.

**Comment by mixn** [comment]
@boudhayan-dev I’m still waiting for more people to chime in on #10. So depends on that. Plus, @Sneezoo’s PR was kind of a dirty hotfix to see if it helps. Him or me or both of us (we’re friends and colleagues) would have to properly integrate it still. But definitely on my radar. :)

Feel free to close this issue, since the above is related to #10 atm. Maybe @Keraito can confirm that this enhancement works as expected — I wouldn’t know why it shouldn’t though. :)

**Comment by Keraito** [comment]
I can try this out tomorrow and report back then 👍

**Comment by boudhayan-dev** [comment]
@mixn Awesome.

**Comment by Keraito** [comment]
Looks all good to me @mixn. One remark, would it be of interest to add some static part to the format so it's easier to index, find, or exclude from a repo through gitignore? Maybe something simple like `foo-cn-ef52f53aab.png`?

**Comment by mixn** [comment]
@Keraito You can always save to a particular folder via `--location` and then ignore that folder, no? :) I think that should be enough.

**Comment by mixn** [comment]
@Keraito I’ll let @boudhayan-dev do the closing. :) Thanks for the input, guys!

**Comment by mixn** [comment]
@boudhayan-dev @Keraito I thought I might [leave this here](https://github.com/mixn/carbon-now-cli/issues/30#issuecomment-422866776), even though this has been closed for a while now. TL;DR: `--target` is a thing now and allows for specific naming of the output image.
