### ISSUE TITLE
Allow reusing the settings of last interactive run

### ISSUE THREAD

**Issue by codepunkt** [mixn/carbon-now-cli#2]
Great project! 👍 

It would be awesome to interactively run until you have a style that you like (if you don't already have one by using carbon.now.sh) and then be able to consistently reuse these settings with an additional commandline flag (that can not be combined with interactive mode).

e.g.
- run -i first, pick your fonts, themes etc
- run -c (cached) later, reusing the latest -i settings.

**Comment by mixn** [comment]
Thank you! ❤️ 

This is — by far — the most requested feature I’ve gotten so far and I can’t believe I have only thought of it *after* publishing, haha. ¯\_(ツ)_/¯

Planning to add it in the next few days. :) Will update!

**Comment by deadcoder0904** [comment]
> run -c (cached) later, reusing the latest -i settings.

I don't think `-c` is required. First time, prompt it & next time onwards use previously used settings.

**Comment by mixn** [comment]
Thinking about how to approach/implement this.

I dislike the idea of automatically taking the last interactive settings as default settings, because that makes exceptions a *real drag*. What do I mean?

Assuming you have settings you love and use 90% of the time, but you’d like to use different settings just once… that’d mean you’d have to run in `-i` for that one case and run the whole thing again (with a dummy file), just to re-set your favorite settings. Sounds annoying to me. :)

I’m dabbling with this idea right now:

`-i` and `-c` together means “run in interactive mode and remember these settings as cached”, then the next time (or whenever) use `-u` to use the cached settings, e.g. `carbon-now foobar.rs -u`.

That’d allow for easy exceptions through just `-i` but fast re-use of favorites through `-u` and rewrites of favorites through `-i -c`.

Thoughts? :)

**Comment by Keraito** [comment]
The main advantage that I can see in "taking the last interactive settings as default settings" for the next run is that the user can decide the default settings *after* playing around with it and know how it looks, while in the suggested implementation he has to opt into it *before* that. Definitely like the idea tho!

Would it be feasible to combine your suggested implementation with having like a "favorites" list where different templates are stored and the user can somehow choose between them? 🤔

**Comment by deadcoder0904** [comment]
@mixn Like your approach :)

> Would it be feasible to combine your suggested implementation with having like a "favorites" list where different templates are stored and the user can somehow choose between them? 🤔

I think this is a bit too much for a CLI but sure :)

**Comment by codepunkt** [comment]
@mixn -i or -i -c or -u sounds great!

**Comment by jwkicklighter** [comment]
Seems like rather than re-using the interactive settings, you could just have a config file somewhere like `~/.carbonnowrc`. Put the current defaults in there if the file doesn't exist, then when an interactive session finished prompt "would you like to save these as your new defaults?"

**Comment by mixn** [comment]
@jwkicklighter That is actually exactly how I wanted do this. :) I’ve always loved [Yeoman’s approach](http://yeoman.io/authoring/storage.html).

**Comment by jwkicklighter** [comment]
I think my main point is that if there is some sort of default settings, it would make sense that they're modifiable by the user (why I suggested that on first run, it creates a settings file to read from). It would also be a helpful feature to have a flag to specify a _different_ config to use, but I don't see the reason to not have the default, no arguments functionality use a config file. Otherwise, the default functionality is only good for the people who don't want to modify a single thing about it, and everyone else will always have to include a flag and a config file location.

**Comment by mixn** [comment]
### So…

I thought (quite a lot) about all things said here (and on Twitter) and just published `1.1.0-0`, which takes everything here into consideration. You can install it via

`npm i -g carbon-now-cli@next`

**What it all does/includes**:

- It will create `~/carbon-now.json` if not present
- Interactive mode will now ask two additional questions

<img width="691" alt="screen shot 2018-07-15 at 16 26 09" src="https://user-images.githubusercontent.com/672237/42734901-e44dd3f0-884b-11e8-8250-5ce9a71c9ed8.png">

- Answering `y` and naming a preset will result in the preset being saved to `~/carbon-now.json`
- A saved preset can be applied like so: `carbon-now foo.js -p presentation`
- The **last** interactive run will be the next **default** (`"latest-preset"` in `~/carbon-now.json`)
  - So running without `-i` will always be pretty :)
- Only one new flag: `-p` ✅
- Only one config file ✅
- Endless presets ✅
- 😍 ✅

Please try it out and report back, I’d appreciate that. :) @codepunkt, @deadcoder0904, @jwkicklighter, @Keraito, @mbuchetics, @sindresorhus (tagging you, cause we DM’d about this feature on Twitter)

**Comment by mixn** [comment]
Documented now:

https://github.com/mixn/carbon-now-cli#presets

I think this issue is hereby ✅. :)

**Comment by jwkicklighter** [comment]
@mixn I wrote up this huge comment and came back to the top to make sure that you hear that I appreciate taking a lot of options into consideration, and love the work you're putting into this. Keep it up! I'm very persistent when it comes to working on usability, and I just want to make sure my thoughts on it are shared, even if nobody likes the idea :)

I like the compromise that you came to, but I'm still not a huge fan of the way that the default command works. (opinion incoming) From a frictionless UX perspective, calling the script with no flag at all should apply the user's favorite preset. If the no flag option always does the last thing that was called from interactive mode, then this can very easily not be the user's favorite preset.

## Use case
- I create my favorite preset using `-i` and save it as `my-fav`.
- Next time I run the tool with no flags, `my-fav` will still be applied.
- I have a one-off where I need to apply some custom settings for some reason.
- Forever into the future, I now must pass `-p my-fav` unless I feel like either copy/pasting `my-fav` into `latest-preset` (not fun) or going through all of the interactive prompts again (waste of time since we already have the options saved somewhere).

I think it's apparent from this example that the UX is definitely not frictionless. At the moment the only way that calling without flags is going to be the user's setup is that they use `-i` to create their preferred setup, and then **never** use `-i` for anything else again (or do one of the manual fixes in my last bullet above).

## Proposal:

- Add another key to the presets object called `default` and in the interactive mode, ask the user if they would also like to save it as default.
- Still save `last-preset` from interactive runs, but either:
  - Make step 1 of `-i` be "Use the settings from last time?"
  - Add another flag that gets passed along with `-i` (something like `-il`?)

**Comment by mixn** [comment]
@jwkicklighter Thanks for the kind words, it means a lot. :)

> Forever into the future, I now must pass `-p my-fav` unless I feel like either copy/pasting my-fav into latest-preset (not fun) or going through all of the interactive prompts again (waste of time since we already have the options saved somewhere).

You are mistaken in the sense that once you reuse a setting via `-p`, you won’t be needing the `-p` any more — since those settings are the default from that point on.

So running a one-off means having to only use `-p` the very next time afterwards, not “forever into the future”. :)

**Comment by jwkicklighter** [comment]
@mixn Great! That's way closer to what I was describing/what I would expect, and I can't complain about that without nitpicking :)
