### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by sindresorhus** [mixn/carbon-now-cli#3]
I use most of my Carbon images on Twitter to illustrate some code snippet. Would be useful if this tool could just put the image in the clipboard instead of writing to disk. For example, if I use the a `--copy` flag.

**Comment by mixn** [comment]
Great idea! :) Note taken, will try working on this soon.

**Comment by tsriram** [comment]
@mixn I'm happy to give this a go if you'd like, assuming you haven't started working on this already :)

**Comment by thib92** [comment]
@mixn Actually this issue relates to what I was talking about on #12.
I think a `--copy` flag would indeed be the best way to integrate it.
@tsriram have you started working on this?

**Comment by itaisteinherz** [comment]
I'm currently working on this, but it seems like a `--copy` flag wouldn't work because there currently isn't a usable cross-platform clipboard module which allows you to copy image.
I think the best solution for the moment being is enabling piping (see #12), and piping the CLI's output to an OS-specific clipboard application, such as `pbpaste` (or any other alternative) on *nix-based systems.

**Comment by mixn** [comment]
@sindresorhus Maybe you could chime in on this since I am using `execa` to run the OS-specific scripts. As mentioned in my comment above, it works flawlessly on macOS — it copies to clipboard and exits properly.

![macos](https://user-images.githubusercontent.com/672237/47011008-0282b500-d141-11e8-8a25-bbaac7821138.gif)

On Linux, it copies properly, but doesn’t exit — it’s like the Promise is `pending` forever.

![linux](https://user-images.githubusercontent.com/672237/47011125-5f7e6b00-d141-11e8-951f-969bb7b8c810.gif)

The relevant code for this can be found [here](https://github.com/mixn/carbon-now-cli/blob/feature/copy-3/cli.js#L219-L240). Am I missing something here?

I’ve also noticed that it exits and copies properly on Linux when I use `execa` without `await`. It doesn’t copy to clipboard on macOS then though.

**Comment by mixn** [comment]
I just published `v1.3.0` where this is available. 🙂🎉 `npm i -g carbon-now-cli` to update to that version.

✅ Cross-OS 😱
✅ Docs are [here](https://github.com/mixn/carbon-now-cli#copying-to-clipboard)

Example of using it with a preset + pasting to Twitter:

![copy-demo](https://user-images.githubusercontent.com/672237/47231996-c19fd000-d3ce-11e8-826a-c400e4e2e930.gif)

Thank you all for chiming in! ❤️
