### ISSUE TITLE
Allow configuring "theme colors" in presets

### ISSUE THREAD

**Issue by nikolasburk** [mixn/carbon-now-cli#46]
The Carbon CLI is really awesome and I love that it's possible to store and reuse a configuration as preset. One thing I'd love to add to the config though is the actual "theme colors" (i.e. what color e.g. variables, operators, keywords, comments, ...).

Basically these options from the Carbon web UI:

![Screenshot 2019-03-26 at 10 39 45](https://user-images.githubusercontent.com/4058327/54986908-cb4be600-4fb3-11e9-8f81-f20bb0d8725d.png)

**Comment by mixn** [comment]
Hey @nikolasburk, thanks for chiming in and the nice words, much appreciated. Big fan of your work! :)

That’s an idea I’ve had since first seeing that this is now fully configurable in the web UI. 

First thought it might not be possible without doing some disgusting DOM traversing through Puppeteer, but just noticed all these values are stored in `localStorage`. :)

You’d likely lose the state/visuals by doing `--open`, but it should fully work through the CLI. 🤔

I’ll try and get to this soon. Quite swamped with work and conf season, but I’m eager to have it as part of the CLI. :)

**Comment by fruit-matrix** [comment]
> 
> 
> The Carbon CLI is really awesome and I love that it's possible to store and reuse a configuration as preset. One thing I'd love to add to the config though is the actual "theme colors" (i.e. what color e.g. variables, operators, keywords, comments, ...).
> 
> Basically these options from the Carbon web UI:
> 
> ![Screenshot 2019-03-26 at 10 39 45](https://user-images.githubusercontent.com/4058327/54986908-cb4be600-4fb3-11e9-8f81-f20bb0d8725d.png)

I want to have make a theme which suits the color scheme of my website. In this above screenshot by @nikolasburk , it seems possible for the user to select whichever colors they want for the variable names, function names, etc. That option seems to be really great. Unfortunately, I cannot see it on the carbon.now.sh website. Has it been removed? :(

**Comment by raveling** [comment]
+1 🙇

**Comment by mixn** [comment]
As I’m finalizing the huge [`v2` release](https://github.com/mixn/carbon-now-cli/issues/83), I’ve decided to run a small beta of it. 🙂 This feature will ship with the official `v2` release, which can currently be tested via

```
npm i carbon-now-cli@beta -g
```

[Documentation 🚀 is here.](https://github.com/mixn/carbon-now-cli/tree/v2/#custom-theme-colors) 🙂

Happy testing and using! Looking forward to your feedback!
`v2` will officially drop any day now. 🥳
