### ISSUE TITLE
SVG fails with headless mode

### ISSUE THREAD

**Issue by redaxmedia** [mixn/carbon-now-cli#54]
Unfortunately, SVG dowloading / renaming fails with headless mode.
 
```
  ✖ Fetching beautiful image
    → ENOENT: no such file or directory, rename '...' -> '...'
    Copying image to clipboard

  Error: Sending code to https://carbon.now.sh went wrong.
```

**Comment by mixn** [comment]
@redaxmedia Thanks for opening one more issue, Henry. 🙂

Yeah, that is [the case for `--headless`](https://github.com/mixn/carbon-now-cli/issues/9#issuecomment-414801757), since it was an edge-case in the beginning anyway. `--headless` leads to a different export mechanism which uses Puppeteer’s `elementHandle.screenshot()` that doesn’t support SVG. SVGs can only be achieved without `--headless`.

I’ll probably put that in the docs still, too. Thank you!

**Comment by redaxmedia** [comment]
Properly, you consider to disable SVG in headless then and return a warning like "not supported in headless mode" ...
