### ISSUE TITLE
Error: Sending code to https://carbon.now.sh went wrong.

### ISSUE THREAD

**Issue by sebestenyb** [mixn/carbon-now-cli#6]
Hi,

Fresh install, OSX High Sierra (10.13.5), firewall turned off (or on, doesn't matter).

```
time carbon-now config/app.php
 ✔ Processing config/app.php
 ✔ Preparing connection
 ↓ Opening in browser [skipped]
 ✖ Fetching beautiful image
   → net::ERR_CONNECTION_CLOSED at https://carbon.now.sh/?bg=none&code=%253C%253Fphp%250A%250Areturn%2520%255B%250A%250A%2520%2520%2520%2520%252F%2A%250A%2520%2520%2520%2520%257C--------------------------------------------------------------------------%250A%2520%2520%252…

  Error: Sending code to https://carbon.now.sh went wrong.

  This is mostly due to:

  – Insensical input like `--start 10 --end 2`
  – Carbon being down or taking too long to respond
  – Your internet connection not working or being too slow

real	0m1.828s
user	0m1.538s
sys	0m0.493s
```

**Comment by mixn** [comment]
Can you try running the exact same thing again, but with the `-o` flag?

Like this:

```
carbon-now config/app.php -o
```

Because it seems like the contents of the file are causing problems with Carbon itself, as can be seen by this https://goo.gl/hb1NwP also giving a `500` error.

Could you try a super simple file and report back? `echo 'Hello world';` will do, haha. 

Thanks. :)

**Comment by sebestenyb** [comment]
I've tried with smaller files, and it worked.
Line count around 170 worked, but around 270 didn't.
So it's probably a character limit, or maybe GET param limit.

**Comment by mixn** [comment]
Probably the latter, yeah. Glad that worked for you and thanks for reporting! :)

**Comment by bimohxh** [comment]
all files cause this error
