### ISSUE TITLE
dependencies needs to be updated 

### ISSUE THREAD

**Issue by DevT0ny** [mixn/carbon-now-cli#66]
![image](https://user-images.githubusercontent.com/47944176/125079475-4b44de00-e0e1-11eb-9d6a-37890567620e.png)

**Comment by mixn** [comment]
As I’m finalizing the huge [`v2` release](https://github.com/mixn/carbon-now-cli/issues/83), I’ve decided to run a small beta of it. 🙂 This issue is covered in that release, so I’ll close it. 🙂 Deps updating is also automated from `v2` onwards.

To install the `v2` beta run

```
npm i carbon-now-cli@beta -g
```

[Docs 🚀 for `v2` can be found here.](https://github.com/mixn/carbon-now-cli/tree/v2/#custom-theme-colors) 🙂 There are tons of new features and breaking changes, so make sure to re-read the docs if you’ve read them previously.

Happy testing and using!
`v2` will officially drop any day now. 🥳
