### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by editid0** [mixn/carbon-now-cli#68]
```
editid@Server:~$ sudo npm i -g carbon-now-cli
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
/usr/local/node-14.15.4/bin/carbon-now -> /usr/local/node-14.15.4/lib/node_modules/carbon-now-cli/cli.js

> puppeteer@1.20.0 install /usr/local/node-14.15.4/lib/node_modules/carbon-now-cli/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: EACCES: permission denied, mkdir '/usr/local/node-14.15.4/lib/node_modules/carbon-now-cli/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/local/node-14.15.4/lib/node_modules/carbon-now-cli/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/usr/local/node-14.15.4/lib/node_modules/carbon-now-cli/node_modules/puppeteer/install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/node-14.15.4/lib/node_modules/carbon-now-cli/node_modules/puppeteer/.local-chromium'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.20.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-17T21_03_15_528Z-debug.log
``` 
I've tried everything, including clearing cache, and trying on a different machine, this is the third machine i've tried, all with the same issue, All ubuntu 20.04 LTS, I've tried installing puppeteer@1.20.0 manually too

**Comment by mixn** [comment]
As I’m finalizing the huge [`v2` release](https://github.com/mixn/carbon-now-cli/issues/83), I’ve decided to run a small beta of it. 🙂 

`v2` is a complete rewrite that now uses [Playwright](https://playwright.dev/) instead of Puppeteer. Playwright supports [real file downloads](https://playwright.dev/docs/downloads) and is well maintained, leading to a more stable UX in the future. Most issues opened in `carbon-now-cli` were due to Puppeteer’s inability to actually wait for the file to download and many other OS inconsistencies & hiccups.

To install the `v2` beta run

```
npm i carbon-now-cli@beta -g
```

[Docs 🚀 for `v2` can be found here.](https://github.com/mixn/carbon-now-cli/tree/v2/#custom-theme-colors) 🙂 There are tons of new features and breaking changes, so make sure to re-read the docs if you’ve read them previously.

Happy testing and using! Looking forward to your feedback!
`v2` will officially drop any day now. 🥳 

P. S: I’m almost embarrassed about how long it took me to start working on `v2`, but at least once I did, I shipped it quite fast. 🙃 No more activity slumps in the future, though. 🤞
