### ISSUE TITLE
Config does not load

### ISSUE THREAD

**Issue by BoKKeR** [mixn/carbon-now-cli#77]
I am running the following 

```./node_modules/.bin/carbon-now --headless --config carbon-config.json src/doc/help.md -t help -l img```

with 

```
{
  "paddingVertical": "56px",
  "paddingHorizontal": "56px",
  "backgroundImage": null,
  "backgroundImageSelection": null,
  "backgroundMode": "color",
  "backgroundColor": "rgba(74,144,226,1)",
  "dropShadow": true,
  "dropShadowOffsetY": "20px",
  "dropShadowBlurRadius": "68px",
  "theme": "verminal",
  "windowTheme": "none",
  "language": "markdown",
  "fontFamily": "Hack",
  "fontSize": "14px",
  "lineHeight": "133%",
  "windowControls": true,
  "widthAdjustment": false,
  "lineNumbers": false,
  "firstLineNumber": 1,
  "exportSize": "2x",
  "watermark": false,
  "squaredImage": false,
  "hiddenCharacters": false,
  "name": "",
  "width": 702
}
```

And the result it 
![help](https://user-images.githubusercontent.com/2664857/166140720-22ad9a19-c024-4e9e-b156-fdce23af2f48.png)

While the same config on the website gives: 

![image](https://user-images.githubusercontent.com/2664857/166140743-67b2d981-0088-4aee-9329-1f1c44285aec.png)

Is there something I am missing? I have the config in the folder I am running the command from. I also tried with global carbon-now

**Comment by mixn** [comment]
@BoKKeR I’m almost done with the large [v2 rewrite](https://github.com/mixn/carbon-now-cli/issues/83) and have started looking at open issues.

The config you’re using might be valid on Carbon itself, but the format for presets in the CLI is different. Take a look at the [default settings here](https://github.com/mixn/carbon-now-cli/blob/master/src/helpers/default-settings.js).

The CLI uses Carbon’s query string param names (e.g., `ds` instead of `dropShadow`, `fs` instead of `fontSize`, etc.), so I don’t have to convert between fitting objects all the time. Also, you’re not specifying an existing preset in your example above; it’s lacking `--preset`.

I’ve tried what you were trying to do with a fresh install and an existing folder structure (the repo itself) + config, and everything works as expected. 

```
npm uninstall -g carbon-now-cli
npm i -g carbon-now-cli
git clone https://github.com/mixn/carbon-now-cli.git
cd carbon-now-cli
carbon-now ./test/test-dummies/_unfold.js --config ./test/test-dummies/_config.json -p dummy-preset -t help -l ~/Desktop
```

results in `~/Desktop/help.png`, which looks as expected (applying the `dummy-preset`):

![help](https://user-images.githubusercontent.com/672237/232253231-98267aec-e316-434f-8e38-ca0926c0dd73.png)
