### ISSUE TITLE
  Error: Protocol error (Page.navigate): Target closed.

### ISSUE THREAD

**Issue by hpl002** [mixn/carbon-now-cli#79]
✔ Processing ./Readme.md
  ✔ Preparing connection
  ↓ Opening in browser [skipped]
  ✖ Fetching beautiful image
    → Protocol error (Page.navigate): Target closed.
    Copying image to clipboard

  Error: Sending code to https://carbon.now.sh went wrong.

  This is mostly due to:

  – Insensical input like `--start 10 --end 2`
  – Carbon being down or taking too long to respond
  – Your internet connection not working or being too slow

  Additional info:

  Error: Protocol error (Page.navigate): Target closed.
  
---  
  node v16.16.0

**Comment by Leetovskiy** [comment]
The same thing is happening to me

**Comment by mixn** [comment]
As I’m finalizing the huge [`v2` release](https://github.com/mixn/carbon-now-cli/issues/83), I’ve decided to run a small beta of it. 🙂 

`v2` is a complete rewrite that now uses [Playwright](https://playwright.dev/) instead of Puppeteer. Playwright supports [real file downloads](https://playwright.dev/docs/downloads) and is well maintained, leading to a more stable UX in the future. Most issues opened in `carbon-now-cli` were due to Puppeteer’s inability to actually wait for the file to download and many other OS inconsistencies & hiccups.

To install the `v2` beta run

```
npm i carbon-now-cli@beta -g
```

[Docs 🚀 for `v2` can be found here.](https://github.com/mixn/carbon-now-cli/tree/v2/#custom-theme-colors) 🙂 There are tons of new features and breaking changes, so make sure to re-read the docs if you’ve read them previously.

Happy testing and using! Looking forward to your feedback!
`v2` will officially drop any day now. 🥳 

P. S: I’m almost embarrassed about how long it took me to start working on `v2`, but at least once I did, I shipped it quite fast. 🙃 No more activity slumps in the future, though. 🤞
