### ISSUE TITLE
stuck in Fetching beautiful image

### ISSUE THREAD

**Issue by FalcoSuessgott** [mixn/carbon-now-cli#80]
Using carbon-now-cli Im stuck in 

```sh
carbon-now assets/base.sh --config assets/carbon-now.json
  ✔ Processing assets/base.sh
  ✔ Preparing connection
  ↓ Opening in browser [skipped]
  ✖ Fetching beautiful image

```

until I cancel it.

Chromium opens but only a tab with `about:blank`, same behavior when using the headless mode. Any debugging tipps or suggestions?

**Comment by mutexdeveloper** [comment]
Same issue.
Closing the chromium window shows error:
```
Error: Protocol error (Performance.enable): Target closed.
Error: Page crashed!
```

**Comment by bosconb** [comment]
same issue is troubling me

**Comment by mutexdeveloper** [comment]
> same issue is troubling me
> ```
> carbon-now --from-clipboard
>   ✔ Processing stdin
>   ✔ Preparing connection
>   ↓ Opening in browser [skipped]
>   ✖ Fetching beautiful image
>     → Protocol error (Page.navigate): Target closed.
>     Copying image to clipboard
> 
>   Error: Sending code to https://carbon.now.sh went wrong.
> 
>   This is mostly due to:
> 
>   – Insensical input like `--start 10 --end 2`
>   – Carbon being down or taking too long to respond
>   – Your internet connection not working or being too slow
> 
>   Additional info:
> 
>   Error: Protocol error (Page.navigate): Target closed.
> ```

#83

**Comment by mixn** [comment]
As I’m finalizing the huge [`v2` release](https://github.com/mixn/carbon-now-cli/issues/83), I’ve decided to run a small beta of it. 🙂 

`v2` is a complete rewrite that now uses [Playwright](https://playwright.dev/) instead of Puppeteer. Playwright supports [real file downloads](https://playwright.dev/docs/downloads) and is well maintained, leading to a more stable UX in the future.

To install the `v2` beta run

```
npm i carbon-now-cli@beta -g
```

[Docs 🚀 for `v2` can be found here.](https://github.com/mixn/carbon-now-cli/tree/v2/#custom-theme-colors) 🙂 Note that there is now an `--engine` flag, allowing you to pick a particular engine and `--disable-headless` to run things in headful mode if preferred. Most issues opened in `carbon-now-cli` were due to Puppeteer’s inability to **actually** wait for the file to **really** download and OS inconsistencies.

Happy testing and using! Looking forward to your feedback!
`v2` will officially drop any day now. 🥳 

P. S: I’m almost embarrassed about how long it took me to start working on `v2`, but at least once I did, I shipped it quite fast. 🙃 No more activity slumps in the future, though. 🤞
